name: build

on: [workflow_dispatch]

jobs:
  windows-msys:
    name: ${{ matrix.config }} Windows ${{ matrix.arch }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
        cc: [gcc]
        include:
          # - arch: x86
          #   msystem: MINGW32
          #   prefix: mingw-w64-i686

          - arch: x86_64
            msystem: MINGW64
            prefix: mingw-w64-x86_64

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: base-devel ${{ matrix.prefix }}-toolchain ${{ matrix.prefix }}-cmake ${{ matrix.prefix }}-ninja ${{ matrix.prefix }}-qt6-base ${{ matrix.prefix }}-qt6-svg ${{ matrix.prefix }}-libxml2 git unzip p7zip
        msystem: ${{ matrix.msystem }}
        path-type: minimal
        release: false
        update: false

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure
      run: |
        cmake -S. --preset DefaultNinja -DCMAKE_BUILD_TYPE=Release -DRADIANT_USE_ASSIMP=ON

    - name: Build
      run: |
        cmake --build --preset DefaultNinja

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SourceRadiant-Windows-${{ matrix.arch }}
        path: install/*
        if-no-files-found: error

  linux:
    name: ${{ matrix.config }} Linux ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]

    steps:
    - name: Install Dependencies
      run: |
          sudo apt-get -qq update
          sudo apt-get -y install mesa-common-dev libjpeg-dev libpng-dev
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.4.2'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        cache: true
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure
      run: |
        cmake -S. --preset DefaultNinja -DCMAKE_BUILD_TYPE=Release -DRADIANT_USE_ASSIMP=ON

    - name: Build
      run: |
        cmake --build --preset DefaultNinja

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SourceRadiant-Linux-${{ matrix.arch }}
        path: install/*
        if-no-files-found: error
